spring.application.name=smid-service
server.port=${SERVER_PORT:8085}

# ==========================================
# CONEXIÓN A BASE DE DATOS (MySQL 8) - smid_db
# ==========================================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/smid_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# JWT (compartida con Gateway y Auth)
# ==========================================
jwt.secret=${JWT_SECRET}

# ==========================================
# LOGGING
# ==========================================
logging.level.org.springframework.web=DEBUG
